=== Using Embedded Ansible to run Automation tasks

{product-title} comes with the https://docs.ansible.com/ansible/latest/modules/nuage_vspk_module.html[Nuage Ansible module] which can be used to manage any Nuage Networks VSP environment and supports all features and Nuage Networks VSP API capabilities.

This Nuage Ansible module can be used from within the {product-title} Automation framework. This chapter will go in more detail of how to set this up and demonstrate this automation.

==== Enabling Embedded Ansible

Before you can use the Nuage Ansible module and the Ansible Automation inside {product-title}, you need to enable the Embedded Ansible functionality. To do this, follow these steps:

1. Log in as an Administrator in {product-title}.

2. Open the {product-title} configuration.

3. Select a {product-title} server.

4. In the *Server Control > Server Roles* make sure the *Embedded Ansible* switch is toggled to *On*.

5. Click the *Save* button.

More details can be found in the {product-title} documentation in the *Introduction to Embedded Ansible* chapter.

==== Create a Git Ansible playbook repository

Once you have enabled Embedded Ansible, the next step is to setup a Git Ansible playbook repository that will contain the playbooks you want to use in your automation tasks. 

Use your preferred Git environment to setup a repository and make sure that repository is reachable by the {product-title} appliance so it can clone the repository locally.

==== Create an Ansible playbook

Inside the Git repository, you will need to have one or more Ansible playbooks. These playbooks contain tasks that need to be executed in order when they are called. 

A very simple playbook that is designed to automatically be executed by the {product-title} Automation framework when a certain Nuage event comes in, could be:

.printout.yaml
[source,yaml]
----
---
- name: Nuage event callback
  hosts: localhost
  connection: local
  gather_facts: False
  vars:
    manageiq_validate_certs: False
  pre_tasks:
  - debug: msg="Running printout"
  roles:
  - role: xlab_si.nuage_miq_automate
    validate_certs: False
  tasks:
  - debug: msg="I am a playbook running as event callback and I am able to access nuage credentials"
  - debug: var=nuage_auth
  - debug: msg="As well as details of the event that triggered me"
  - debug: var=event
  - debug: msg="So I'm now ready to do some work!"
----

This playbook will capture the event and print out some information about the event in the automation log file. 

The important part to note in this playbook is that it includes a role called `xlab_si.nuage_miq_automate`. This role is provided by Nuage Networks to support the Ansible integration. It's purpose is to get the necessary information from {product-title} and provide it as Ansible facts to the other tasks in the playbook.

A more advanced playbook, using the Nuage Ansible module, looks like:

.printout-and-fetch.yaml
----
---
- name: Nuage event callback
  hosts: localhost
  connection: local
  gather_facts: False
  vars:
    manageiq_validate_certs: False
  pre_tasks:
  - debug: msg="Running printout with fetch entity"
  roles:
  - xlab_si.nuage_miq_automate
  tasks:
  - debug: msg="I am a playbook running as event callback and I am able to access nuage credentials"
  - debug: var=nuage_auth
  - debug: msg="As well as details of the event that triggered me"
  - debug: var=event
  - debug: msg="So I'm now ready to do some work!"

  - name: Fetch entity from Nuage
    nuage_vspk:
      auth: "{{ nuage_auth }}"
      type: "{{ event.entity_type | capitalize }}"
      command: find
      id: "{{ event.entity.ID }}"
    register: entity
    when: event.type == 'CREATE' or event.type == 'UPDATE'
  - debug: var=entity
----

In this playbook, the Nuage VSPK Ansible module is used to fetch the data from the Nuage environment on the entity on which the event happened. 

More examples, and details on the `xlab_si.nuage_miq_automate` role, can be found in our https://github.com/nuagenetworks/manageiq-ansible-playbooks[Example GitHub repository].

==== Adding a Ansible playbook repository to {product-title}

After enabling the Embedded Ansible functionality and creating your playbooks, the next step is to add the Ansible playbook repository to {product-title}. This can be done following these steps:

1. In {product-title}, open *Automation > Ansible > Repositories*.

2. Click *Configuration > Add New Repository*.

3. Provide a *Name*, select the SCM type to *GIT* and fill in the *URL* to your Git repository. If you have specific credentials that are needed for the repository, or a specific branch, please provide that information too.

4. Click *Add*.

This will make the {product-title} appliance clone the repository locally. Once that has been completed, you can check the *Automation > Ansible > Playbooks* page to see your playbooks showing up.

==== Setting up the automation

Now that we have the playbooks available in {product-title}, you can use them in your Automation.

First, you will need to create an Automate domain:

. Go to *Automation > Automate > Explorer*.

. Select *Datastore*.

. Click on *Configuration* and select *Add a New Domain*.

. Enter a *Name* and *Enable* the Automate Domain.

. Click *Add*.

Using this Automate Domain, you can either configure your own set of Namespaces, Classes and instances; or you can copy the existing examples and modify them to your needs. The following section describes the copy method:

. Select an example *Automate Instance* in the *ManageIQ (Locked) > System > Event > EmsEvent > Nuage* Automate Class. 

. Click *Configuration > Copy this instance*.

. Select your new *Automate Domain* and where you want to copy it to.

Now that you have a copied *Automate Instance*, you can update that class with your own Nuage Authentication information by following these steps:

. Select the *Automate Class* to which your new *Automate Instance* belongs.

. Select the *Schema* tab.

. Click *Configuration > Edit this Class*.

. Fill in the *nuage_username*, *nuage_password*, *nuage_enterprise* and *nuage_url* with the appropriate information of your environment.

. Click *Save* to save the information.

Setup the playbook that needs to be executed:

. Select the *Method* tab on the *Automate Class*.

. Click *Configuration > Add New Method*.

. Select the *Type* to be *playbook*.

. Provide a *Name*. 

. Select your Ansible repository.

. Select the Ansible playbook.

. Select the *Machine Credentials* as *CFME Default Credential*.

. If your {product-title} server and/or the Nuage VSD is using self-signed certificates or untrusted certificates, add an *Input Parameter* called *manageiq_validate_certs* with a default value *False*.

. Click *Add*.

The last step is to add the method to the Automate Instance:

. Select the previously created *Automate Instance*.

. Click *Configuration > Edit this Instance*.

. In one of the *(methX)* fields, put the name of the *Method* you just created.

. Click *Save*.

This will setup an automated event handler that will execute the playbook when an event comes in with the name of the *Automate Instance* that you copied. 

In case you want to execute a playbook based on an event which has not been previously defined, you can create a new *Automate Instance* with the name of the event on which you want to execute the playbook.

For instance, if you want to make sure a playbook runs every time a Nuage Job is updated, you can create an *Automate Instance* with the name *nuage_job_update*.

