== Overview

The Nuage Networks Provider for Red Hat CloudForms provides IT and Network administrators the capabilities to integrate a Nuage Networks VSP environment into Red Hat CloudForms. Nuage Networks VSP provides a software-defined networking (SDN) solution which delivers policy-based automation across the network. Its components can be used to optimize datacenter, cloud and software-defined WAN operations, and to automate security policies and remediation. For more information on Nuage Networks VSP, please visit http://nuagenetworks.net[the Nuage Networks website].

Key features include:

* Monitoring of all events and alarms from the Nuage VSP environment.
* Leveraging events and alarms for automation and reporting.
* Visibility in the Nuage VSP tenants.
* Visibility in the Nuage VSP overlay networks.
* Visibility in the Nuage VSP security groups.
* Visibility in the Nuage VSP ports.
* Visibility in the relationships between the different Nuage entities.
* Display the above relationships.
* Display the relationship between Nuage VSP ports and Virtual Machines in the other providers.
* Automatic targeted refresh of entities on events.

